apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mapeo-cosmosdb-kafka"},"name":"mapeo-cosmosdb-kafka","namespace":"kafka-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mapeo-cosmosdb-kafka"}},"template":{"metadata":{"labels":{"app":"mapeo-cosmosdb-kafka"},"name":"mapeo-cosmosdb-kafka"},"spec":{"containers":[{"env":[{"name":"AZURE_COSMOSDB_URI","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_URI","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMODB_DATABASE","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMODB_DATABASE","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_COMPANY","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_COMPANY","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_CAT","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_CAT","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_LEGAL_REP","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_LEGAL_REP","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_ORDERS","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_ORDERS","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_PAC","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_PAC","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_TITULATES","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_TITULATES","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_COLLECTION_ZSUB_FINANCES","valueFrom":{"configMapKeyRef":{"key":"AZURE_COSMOSDB_COLLECTION_ZSUB_FINANCES","name":"configmap-kafka-cosmosdb"}}},{"name":"SERVER_PORT","valueFrom":{"configMapKeyRef":{"key":"SERVER_PORT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_BOOTSTRAP_SERVERS","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_BOOTSTRAP_SERVERS","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_LEGAL_REP_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_LEGAL_REP_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_FINANCES_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_FINANCES_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_ORDERS_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_ORDERS_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_COMPANY_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_COMPANY_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_PAC_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_PAC_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_CAT_TDOCBP","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_CAT_TDOCBP","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_TOPIC_Z_SUB_TITULATE_DT","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_TOPIC_Z_SUB_TITULATE_DT","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL","name":"configmap-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_PROPERTIES_SASL_MECHANISM","valueFrom":{"configMapKeyRef":{"key":"SPRING_KAFKA_PROPERTIES_SASL_MECHANISM","name":"configmap-kafka-cosmosdb"}}},{"name":"AZURE_COSMOSDB_KEY","valueFrom":{"secretKeyRef":{"key":"AZURE_COSMOSDB_KEY","name":"secret-kafka-cosmosdb"}}},{"name":"SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG","valueFrom":{"secretKeyRef":{"key":"SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG","name":"secret-kafka-cosmosdb"}}}],"image":"749892430062.dkr.ecr.us-east-1.amazonaws.com/comfama/mapeo-cosmosdb-kafka:latest","imagePullPolicy":"Always","name":"conexion-hana","resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","securityContext":{}}}}}
  labels:
    app: mapeo-cosmosdb-kafka
  name: mapeo-cosmosdb-kafka
  namespace: kafka-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mapeo-cosmosdb-kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mapeo-cosmosdb-kafka
      name: mapeo-cosmosdb-kafka
    spec:
      containers:
        - env:
            - name: AZURE_COSMOSDB_URI
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_URI
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMODB_DATABASE
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_COMPANY
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_COMPANY
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_CAT
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_CAT
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_LEGAL_REP
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_LEGAL_REP
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_ORDERS
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_ORDERS
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_PAC
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_PAC
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_TITULATES
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_TITULATES
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_COLLECTION_ZSUB_FINANCES
              valueFrom:
                configMapKeyRef:
                  key: AZURE_COSMOSDB_COLLECTION_ZSUB_FINANCES
                  name: configmap-kafka-cosmosdb
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_LEGAL_REP_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_LEGAL_REP_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_FINANCES_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_FINANCES_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_ORDERS_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_ORDERS_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_COMPANY_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_COMPANY_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_PAC_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_PAC_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_CAT_TDOCBP
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_CAT_TDOCBP
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_TOPIC_Z_SUB_TITULATE_DT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_TOPIC_Z_SUB_TITULATE_DT
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
                  name: configmap-kafka-cosmosdb
            - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
                  name: configmap-kafka-cosmosdb
            - name: AZURE_COSMOSDB_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_COSMOSDB_KEY
                  name: secret-kafka-cosmosdb
            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  key: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
                  name: secret-kafka-cosmosdb
          image: 749892430062.dkr.ecr.us-east-1.amazonaws.com/comfama/mapeo-cosmosdb-kafka:latest
          imagePullPolicy: Always
          name: conexion-hana
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
