apiVersion: v1
data:
  AZURE_COSMOSDB_KEY: 0
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: 0
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"secret-kafka-cosmosdb","namespace":"kafka-dev"},"stringData":{"AZURE_COSMOSDB_KEY":"2Q9BPWQgVd3GYXDzpVGymmpdtzmlu9iOpQ54jgR1maMMNzhIgZvV2qIX7DKFKszQuUvvj9uRDhoRACDbcnLK4g==","SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG":"org.apache.kafka.common.security.scram.ScramLoginModule required username='adminuserkafka' password='admin_kafka_comfama*';"},"type":"Opaque"}
  name: secret-kafka-cosmosdb
  namespace: kafka-dev
type: Opaque
